Feature/login
couplog/front-end pull request #11
Opened 2023-06-08 12:07 UTC by leeyedam

로그인 api연결 및 디자인 스타일 추가

2023-06-08 12:52 UTC, hyeone999 requested changes

2023-06-08 12:52 UTC, hyeone999 commented on frontend/src/screens/ConnectPartner.tsx
>              keyboardType="phone-pad"
인증 코드의 경우에는 문자 + 숫자의 조합인데 키보드 타입 변경 해야할 것 같아요!
```js
keyboardType="phone-pad"
```

2023-06-08 12:52 UTC, hyeone999 commented on frontend/src/screens/ConnectPartner.tsx
>      color: 'red',
#E53C3C 컬러 확인 부탁드립니다

2023-06-08 12:53 UTC, hyeone999 requested changes

2023-06-08 12:56 UTC, hyeone999 commented on frontend/src/screens/Login.tsx
>            )}
로그인 실패시 조건부 렌더링 처리가 되었을까요?
코드상으로는 확인이 안되는 것 같습니다!!
`존재하지 않는 번호입니다.`, `비밀번호가 틀렸습니다.`

2023-06-08 12:57 UTC, hyeone999 commented on frontend/src/screens/Login.tsx
>      color: 'red',
피그마 컬러확인 부탁드려요!

2023-06-09 00:46 UTC, hyeone999 commented on frontend/src/screens/Login.tsx
> +    navigation.navigate('RegisterInfoScreen');
`RegisterPhoneNum` 스크린으로 navigate 시켜주세요!
그리고 함수명이 조금 더 명시적이면 좋을거 같아요 ex) handleNavigateToSignup

2023-06-09 00:59 UTC, hyeone999 commented on frontend/src/screens/Login.tsx
> +  const handleNavigation = () => {
```js
const handleComplete = async (data: LoginFormData) => {
  try {
    const res = await handleLogin(data);
    console.log(res);
  } catch (err) {
    const errorCode = err.response.data.code;
    handleErrorResponse(errorCode);
  }
};

const handleErrorResponse = (errorCode: string) => {
  console.log(errorCode);
  if (errorCode === 'C006') {
    setPhoneNumberError(true);
  } else if (errorCode === 'C009') {
    setPasswordError(true);
  } else {
    Alert.alert('에러 메시지를 처리하는 로직');
  }
};
```
1. Async/await 사용 -> 에러 처리 보다 명확하게 가능 + 효율적인 비동기처리

2. 에러 처리 함수 분기처리 -> handleComplete() 함수에 로직을 한번에 넣는 것 보다 에러 처리 로직을 분기하여 복잡하지 않게 코드를 구현 + 간결하고 가독성을 좋게

3. `err.response.data.code` 반복하여 사용하는 것 보다는 ` const errorCode = err.response.data.code;`로 선언해줘서 재사용해도 좋아보입니다 👍

2023-06-09 01:09 UTC, hyeone999 commented on frontend/src/screens/Login.tsx
> +
```js
const handleComplete = async (data: LoginFormData) => {
  try {
    const res = await handleLogin(data);
    console.log(res);
  } catch (err) {
    const errorCode = err.response.data.code;
    handleErrorResponse(errorCode);
  }
};

const handleErrorResponse = (errorCode: string) => {
  console.log(errorCode);
  if (errorCode === 'C006') {
    setPhoneNumberError(true);
  } else if (errorCode === 'C009') {
    setPasswordError(true);
  } else {
    Alert.alert('에러 메시지를 처리하는 로직');
  }
};
```
1. Async/await 사용 -> 에러 처리 보다 명확하게 가능 + 효율적인 비동기처리

2. 에러 처리 함수 분기처리 -> handleComplete() 함수에 로직을 한번에 넣는 것 보다 에러 처리 로직을 분기하여 복잡하지 않게 코드를 구현 + 간결하고 가독성을 좋게

3. `err.response.data.code` 반복하여 사용하는 것 보다는 ` const errorCode = err.response.data.code;`로 선언해줘서 재사용해도 좋아보입니다 👍

4. 마지막에 else문에 구현한 얼럿은 필요한 기능인가요? 만약 필요하지 않다면 삭제하셔도 될 것 같아요 :)

2023-06-09 01:10 UTC, hyeone999 commented on frontend/src/screens/Login.tsx
> +  };
```js
const handleComplete = async (data: LoginFormData) => {
  try {
    const res = await handleLogin(data);
    console.log(res);
  } catch (err) {
    const errorCode = err.response.data.code;
    handleErrorResponse(errorCode);
  }
};

const handleErrorResponse = (errorCode: string) => {
  console.log(errorCode);
  if (errorCode === 'C006') {
    setPhoneNumberError(true);
  } else if (errorCode === 'C009') {
    setPasswordError(true);
  } else {
    Alert.alert('에러 메시지를 처리하는 로직');
  }
};
```
1. Async/await 사용 -> 에러 처리 보다 명확하게 가능 + 효율적인 비동기처리

2. 에러 처리 함수 분기처리 -> handleComplete() 함수에 로직을 한번에 넣는 것 보다 에러 처리 로직을 분기하여 복잡하지 않게 코드를 구현 + 간결하고 가독성을 좋게

3. `err.response.data.code` 반복하여 사용하는 것 보다는 ` const errorCode = err.response.data.code;`로 선언해줘서 재사용해도 좋아보입니다 👍

4. 마지막에 else문에 구현한 얼럿은 필요한 기능인가요? 만약 필요하지 않다면 삭제하셔도 될 것 같아요 :)

2023-06-09 15:36 UTC, leeyedam commented on frontend/src/screens/Login.tsx
> +  };
현중님! 원래는 로그인 페이지 인풋들 상태값 없으면 버튼 비활성화 되는 부분까지 만들고 올리려고했는데,
제가 현중님꺼 코드보고 똑같이 구현해도 계속 작동이 안돼더라고요..ㅜㅜ 그래서 일단은 여기까지 머지하고
다음에 수정해야할 것 같습니다🥹

2023-06-10 02:17 UTC, hyeone999 commented
안녕하세요 예담님!

아마 제 코드의 경우에는 로그인 input 로직과는 달라서 코드를 비슷하게 사용하셔도 적용이 안된 것 같습니다!
말씀해주신대로, 전화번호 & 비밀번호 Input의 value가 없다면 버튼이 비활성화 되게끔 하는 로직을 

```js
  const {
    control,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm({
    defaultValues: {
      phone: '',
      password: '',
    },
  });


disabled={!watch('phone') || !watch('password')}
```
이렇게 구현해보시면 어떨까요? :)

2023-06-10 03:06 UTC, merged